name: apptruyenonline
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.15
  flutter_launcher_icons: "^0.13.1"
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.0
  dio: ^5.0.0
  image_picker: ^0.8.4+4


flutter_icons:
  android: true
  ios: true
  image_path: "assets/7939054.png"

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/mock_data.json
    - assets/300.jpg
    - assets/avt.png
    - assets/metruyen.jpg
    - assets/bn1.jpg
    - assets/bn2.jpg
    - assets/bn3.jpg
    - assets/bn4.jpg
    - assets/bn5.jpg
    - assets/bn6.jpg