name: apptruyenonline
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ^3.5.0
dependencies:
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.14.1
  cached_network_image: ^3.2.0
  image_picker: ^1.1.2
  provider: ^6.0.0
  audioplayers: ^6.1.0
  image: ^4.2.0
  intl: ^0.19.0
  pay: ^1.1.0
  url_launcher: ^6.1.0
  flutter_image_compress: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/7939054.png"

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/mock_data.json
    - assets/300.jpg
    - assets/avt.png
    - assets/metruyen.jpg
    - assets/bn1.jpg
    - assets/bn2.jpg
    - assets/bn3.jpg
    - assets/bn4.jpg
    - assets/bn5.jpg
    - assets/bn6.jpg
    - assets/ambient_c_motion.mp3
    - assets/level/Đấu Khí.webp
    - assets/level/Đấu Giả.png
    - assets/level/Đấu Sư.webp
    - assets/level/Đại Đấu Sư.webp
    - assets/level/Đấu Linh.webp
    - assets/level/Đấu Vương.webp
    - assets/level/Đấu Hoàng.webp
    - assets/level/Đấu Tông.webp
    - assets/level/Đấu Tôn.webp
    - assets/level/Đấu Thánh.webp
    - assets/level/Đấu Đế.webp
