name: apptruyenonline
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.14.1
  cached_network_image: ^3.2.0
  image_picker: ^1.1.2
  provider: ^6.0.0
  audioplayers: ^6.1.0
  image: ^4.2.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/7939054.png"
#  Luyện Khí.webp
#
#  Trúc Cơ.webp
#
#  Kết Đan.webp
#
#  Nguyên Anh.webp
#
#  Hóa Thần.webp
#
#  Luyện Hư.webp
#
#  Đại Thừa.webp
flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/mock_data.json
    - assets/300.jpg
    - assets/avt.png
    - assets/metruyen.jpg
    - assets/bn1.jpg
    - assets/bn2.jpg
    - assets/bn3.jpg
    - assets/bn4.jpg
    - assets/bn5.jpg
    - assets/bn6.jpg
    - assets/ambient_c_motion.mp3
    - assets/level/Luyện Khí.webp
    - assets/level/Trúc Cơ.webp
    - assets/level/Kết Đan.webp
    - assets/level/Nguyên Anh.webp
    - assets/level/Hóa Thần.webp
    - assets/level/Luyện Hư.webp
    - assets/level/Đại Thừa.webp