name: apptruyenonline
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^0.13.3


flutter:
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/mock_data.json
    - assets/300.jpg
    - assets/avt.png
    - assets/metruyen.jpg
