name: Build and Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Setup môi trường Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # Thay bằng phiên bản Flutter bạn dùng, ví dụ "3.13.0"

      # Bước 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Bước 4: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Bước 5: Upload APK to GitHub Releases
      - name: Upload APK to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.run_number }}
          name: "Release Build ${{ github.run_number }}"
          body: "APK built from latest push to main branch."
          draft: false
          prerelease: false
